### ISSUE TITLE
서치 UI 및 기능 구현

### ISSUE THREAD

**Issue by robinyoon-dev** [robinyoon-dev/typescript-project#14]
# Description
채널명을 검색할 수 있는 UI를 구현하자.

# Todo
- [x] api에서 authenticate와 search 기능 분리하기.
- [ ] oauth.js를 ts로 바꾸기.
- [ ]  UI 구현
- [x]  검색 후 검색 결과가 나올 수 있게 만들기.

# etc
branch명: issue14

**Comment by robinyoon-dev** [comment]
# memo
```typescript
const {google} = require('googleapis');
const youtube = google.youtube('v3');

async function main() {
  const auth = new google.auth.GoogleAuth({
    // Scopes can be specified either as an array or as a single, space-delimited string.
    scopes: [
      'https://www.googleapis.com/auth/youtube',
      'https://www.googleapis.com/auth/youtube.force-ssl',
      'https://www.googleapis.com/auth/youtube.readonly',
      'https://www.googleapis.com/auth/youtubepartner',
    ],
  });

  // Acquire an auth client, and bind it to all future calls
  const authClient = await auth.getClient();
  google.options({auth: authClient});

  // Do the magic
  const res = await youtube.search.list({
    // Filter on resources belonging to this channelId.
    channelId: 'placeholder-value',
    // Add a filter on the channel search.
    channelType: 'placeholder-value',
    // Filter on the livestream status of the videos.
    eventType: 'placeholder-value',
    // Search owned by a content owner.
    forContentOwner: 'placeholder-value',
    // Restrict the search to only retrieve videos uploaded using the project id of the authenticated user.
    forDeveloper: 'placeholder-value',
    // Search for the private videos of the authenticated user.
    forMine: 'placeholder-value',
    // Filter on location of the video
    location: 'placeholder-value',
    // Filter on distance from the location (specified above).
    locationRadius: 'placeholder-value',
    // The *maxResults* parameter specifies the maximum number of items that should be returned in the result set.
    maxResults: 'placeholder-value',
    // *Note:* This parameter is intended exclusively for YouTube content partners. The *onBehalfOfContentOwner* parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their video and channel data, without having to provide authentication credentials for each individual channel. The CMS account that the user authenticates with must be linked to the specified YouTube content owner.
    onBehalfOfContentOwner: 'placeholder-value',
    // Sort order of the results.
    order: 'placeholder-value',
    // The *pageToken* parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken and prevPageToken properties identify other pages that could be retrieved.
    pageToken: 'placeholder-value',
    // The *part* parameter specifies a comma-separated list of one or more search resource properties that the API response will include. Set the parameter value to snippet.
    part: 'placeholder-value',
    // Filter on resources published after this date.
    publishedAfter: 'placeholder-value',
    // Filter on resources published before this date.
    publishedBefore: 'placeholder-value',
    // Textual search terms to match.
    q: 'placeholder-value',
    // Display the content as seen by viewers in this country.
    regionCode: 'placeholder-value',
    // Search related to a resource.
    relatedToVideoId: 'placeholder-value',
    // Return results relevant to this language.
    relevanceLanguage: 'placeholder-value',
    // Indicates whether the search results should include restricted content as well as standard content.
    safeSearch: 'placeholder-value',
    // Restrict results to a particular topic.
    topicId: 'placeholder-value',
    // Restrict results to a particular set of resource types from One Platform.
    type: 'placeholder-value',
    // Filter on the presence of captions on the videos.
    videoCaption: 'placeholder-value',
    // Filter on videos in a specific category.
    videoCategoryId: 'placeholder-value',
    // Filter on the definition of the videos.
    videoDefinition: 'placeholder-value',
    // Filter on 3d videos.
    videoDimension: 'placeholder-value',
    // Filter on the duration of the videos.
    videoDuration: 'placeholder-value',
    // Filter on embeddable videos.
    videoEmbeddable: 'placeholder-value',
    // Filter on the license of the videos.
    videoLicense: 'placeholder-value',
    // Filter on syndicated videos.
    videoSyndicated: 'placeholder-value',
    // Filter on videos of a specific type.
    videoType: 'placeholder-value',
  });
  console.log(res.data);

  // Example response
  // {
  //   "etag": "my_etag",
  //   "eventId": "my_eventId",
  //   "items": [],
  //   "kind": "my_kind",
  //   "nextPageToken": "my_nextPageToken",
  //   "pageInfo": {},
  //   "prevPageToken": "my_prevPageToken",
  //   "regionCode": "my_regionCode",
  //   "tokenPagination": {},
  //   "visitorId": "my_visitorId"
  // }
}

main().catch(e => {
  console.error(e);
  throw e;
});
```

**Comment by robinyoon-dev** [comment]
# 현재 상황
searchJS.js
```javascript
import { google } from 'googleapis'

export default function handler(req, res) {
  if (req.method === 'POST') {
    const data = req.body
    const { authData, text } = data

    console.log("---authData---");
    console.log(authData);
    let searchResult = runSample(authData, text)
    res.status(200).json({ searchResult })
  }
}

async function runSample(client, text) {
  //initialize the Youtube API library
  const youtube = google.youtube('v3')

  const res = youtube.search.list({
    auth: client,
    part: 'snippet',
    type: 'channel',
    q: text,
  })

  res
    .then((response) => {
      let searchResults = response.data.items

      if (searchResults.length === 0) {
        return '검색된 채널이 없습니다'
      } else {
        let result = JSON.stringify(response.data.items[0], null, 4)

        console.log('첫번째 결과')
        console.log(result)
        return result
      }
    })
    .catch((err) => {
      console.error('에러났어: ' + err)
      return
    })
}
```

결과: TypeError: authClient.request is not a function

**Comment by robinyoon-dev** [comment]
# 클라이언트 사이드에 서치 결과 불러오기 성공!

searchJS.js
```javascript
import { google } from 'googleapis'

export default async function handler(req, res) {
  if (req.method === 'POST') {
    const data = req.body
    const { authData, text } = data

    try {
      let searchResult = await runSample(authData, text)
      res.status(200).json({ searchResult })
    } catch (error) {
      console.error('에러났어: ' + error)
      res.status(500).json({ error: 'Internal server error' })
    }
  }
}

async function runSample(client, text) {
  //initialize the Youtube API library
  const youtube = google.youtube('v3')
  // Create an authentication client
  const auth = new google.auth.OAuth2(
    client.clientId,
    client.clientSecret,
    client.redirectUri,
  )
  auth.setCredentials(client.credentials)
  return new Promise((resolve, reject) => {
    youtube.search.list(
      {
        auth: auth,
        part: 'snippet',
        type: 'channel',
        q: text,
      },
      function (err, response) {
        if (err) {
          console.error('에러났어: ' + err)
          reject(err)
        } else {
          let searchResults = response.data.items

          if (searchResults.length === 0) {
            resolve([])
          } else {
            console.log(searchResults)
            resolve(searchResults)
          }
        }
      },
    )
  })
}

```

![image](https://github.com/robinyoon-dev/typescript-project/assets/107087958/7d7970e4-f89e-4ad0-94b9-9a31a306c0b7)

**Comment by robinyoon-dev** [comment]
# issue: 정보가 부족
내가 참고하는 것
![image](https://github.com/robinyoon-dev/typescript-project/assets/107087958/98d06172-9c45-495d-9abd-e4da9b7956ff)

그러나 나한테는 정보가 이것만 있다.
```
[
  {
    kind: 'youtube#searchResult',
    etag: 'QUDOsxsKDBT45r6TDjGBic1EUhY',
    id: { kind: 'youtube#channel', channelId: 'UCUj6rrhMTR9pipbAWBAMvUQ' },      
    snippet: {
      publishedAt: '2014-09-30T07:40:14Z',
      channelId: 'UCUj6rrhMTR9pipbAWBAMvUQ',
      title: '침착맨',
      description: '반갑습니다. 오늘도 즐거운 날입니다.',
      thumbnails: [Object],
      channelTitle: '침착맨',
      liveBroadcastContent: 'upcoming',
      publishTime: '2014-09-30T07:40:14Z'
    }
  },
  {
    kind: 'youtube#searchResult',
    etag: 'DAeSs0dN9F3lNU-fvbmWFcwVVq0',
    id: { kind: 'youtube#channel', channelId: 'UCC1LvVTX2ySKYjeIXkAtvsQ' },      
    snippet: {
      publishedAt: '2020-06-05T09:51:27Z',
      channelId: 'UCC1LvVTX2ySKYjeIXkAtvsQ',
      title: '침착맨 플러스',
      description: '침착맨 채널에 미처 다 공개되지 않은 영상을 올립니다.',       
      thumbnails: [Object],
      channelTitle: '침착맨 플러스',
      liveBroadcastContent: 'none',
      publishTime: '2020-06-05T09:51:27Z'
    }
  },
  {
    kind: 'youtube#searchResult',
    etag: 'cKRPPCcuWwycfwne2xE9ma8Q1Ys',
    id: { kind: 'youtube#channel', channelId: 'UCewitUbsXnyjvJjGgxa0IYw' },      
    snippet: {
      publishedAt: '2019-05-11T13:38:24Z',
      channelId: 'UCewitUbsXnyjvJjGgxa0IYw',
      title: '침착맨 원본 박물관',
      description: '침착맨 생방송의 원본을 올립니다.',
      thumbnails: [Object],
      channelTitle: '침착맨 원본 박물관',
      liveBroadcastContent: 'none',
      publishTime: '2019-05-11T13:38:24Z'
    }
  },
  {
    kind: 'youtube#searchResult',
    etag: 'BuKLsrPesq842ezqAOSl22Wbv_0',
    id: { kind: 'youtube#channel', channelId: 'UCwHTeh9tjyFNfLRQKn5F_uw' },      
    snippet: {
      publishedAt: '2019-12-26T04:58:59Z',
      channelId: 'UCwHTeh9tjyFNfLRQKn5F_uw',
      title: '누군가는 해야하잖아',
      description: '한국인 newgooya@gmail.com.',
      thumbnails: [Object],
      channelTitle: '누군가는 해야하잖아',
      liveBroadcastContent: 'none',
      publishTime: '2019-12-26T04:58:59Z'
    }
  },
  {
    kind: 'youtube#searchResult',
    etag: 'Yc9Vv4xhe1min4MZDnX_SYxDweQ',
    id: { kind: 'youtube#channel', channelId: 'UCxQXvvaqwA2NzPXs5775ogw' },      
    snippet: {
      publishedAt: '2020-12-08T05:47:36Z',
      channelId: 'UCxQXvvaqwA2NzPXs5775ogw',
      title: 'M드로메다 스튜디오',
      description: '안드로메다급 재미!   Bottle flavored. 비즈니스 문의: mdromedastudio@gmail.com mdromeda@mbc.co.kr.',
      thumbnails: [Object],
      channelTitle: 'M드로메다 스튜디오',
      liveBroadcastContent: 'upcoming',
      publishTime: '2020-12-08T05:47:36Z'
    }
  }
]
```

**Comment by robinyoon-dev** [comment]
# memo 각 결과에 구독자수 합치기
searchJS.js
```
import { google } from 'googleapis'

export default async function handler(req, res) {
  if (req.method === 'POST') {
    const data = req.body
    const { authData, text } = data

    try {
      let searchResult = await runSample(authData, text)
      res.status(200).json({ searchResult })
    } catch (error) {
      console.error('에러났어: ' + error)
      res.status(500).json({ error: 'Internal server error' })
    }
  }
}

async function runSample(client, text) {
  //initialize the Youtube API library
  const youtube = google.youtube('v3')
  // Create an authentication client
  const auth = new google.auth.OAuth2(
    client.clientId,
    client.clientSecret,
    client.redirectUri,
  )
  auth.setCredentials(client.credentials)
  return new Promise((resolve, reject) => {
    youtube.search.list(
      {
        auth: auth,
        part: 'snippet',
        type: 'channel',
        q: text,
      },
      function (err, response) {
        if (err) {
          console.error('에러났어: ' + err)
          reject(err)
        } else {
          let searchResults = response.data.items

          if (searchResults.length === 0) {
            resolve([])
          } else {
            const promises = searchResults.map((searchResult) => {
              return new Promise((resolve, reject) => {
                youtube.channels.list(
                  {
                    auth: auth,
                    part: 'statistics',
                    id: searchResult.id.channelId,
                  },
                  function (err, response) {
                    if (err) {
                      console.error('구독자수 불러오기 실패')
                      reject(err)
                    } else {
                      let channel = response.data.items[0]

                      let subscriberCount = channel.statistics.subscriberCount

                      resolve({
                        searchResult: searchResult,
                        subscriberCount: subscriberCount,
                      })
                    }
                  },
                )
              })
            })

            // Wait for all promises to resolve
            Promise.all(promises)
              .then((finalResults) => {
                console.log('------finalResults----')
                console.log(finalResults)
                resolve(finalResults)
              })
              .catch((error) => {
                console.error('에러났어: ' + error)
                reject(error)
              })
          }
        }
      },
    )
  })
}

```


```
------finalResults----
[
  {
    searchResult: {
      kind: 'youtube#searchResult',
      etag: 'QUDOsxsKDBT45r6TDjGBic1EUhY',
      id: [Object],
      snippet: [Object]
    },
    subscriberCount: '2180000'
  },
  {
    searchResult: {
      kind: 'youtube#searchResult',
      etag: 'DAeSs0dN9F3lNU-fvbmWFcwVVq0',
      id: [Object],
      snippet: [Object]
    },
    subscriberCount: '617000'
  },
  {
    searchResult: {
      kind: 'youtube#searchResult',
      etag: 'oLIihQ9ZDyNAhJ6nklJKFy4l1gw',
      id: [Object],
      snippet: [Object]
    },
    subscriberCount: '294000'
  },
  {
    searchResult: {
      kind: 'youtube#searchResult',
      etag: 'BuKLsrPesq842ezqAOSl22Wbv_0',
      id: [Object],
      snippet: [Object]
    },
    subscriberCount: '43000'
  },
  {
    searchResult: {
      kind: 'youtube#searchResult',
      etag: 'Yc9Vv4xhe1min4MZDnX_SYxDweQ',
      id: [Object],
      snippet: [Object]
    },
    subscriberCount: '580000'
  }
]
```

**Comment by robinyoon-dev** [comment]
# 구독자 수 불러오기 성공
```javascript
import { google } from 'googleapis'

export default async function handler(req, res) {
  if (req.method === 'POST') {
    const data = req.body
    const { authData, text } = data

    try {
      let searchResult = await runSample(authData, text)
      res.status(200).json({ searchResult })
    } catch (error) {
      console.error('에러났어: ' + error)
      res.status(500).json({ error: 'Internal server error' })
    }
  }
}

async function runSample(client, text) {
  //initialize the Youtube API library
  const youtube = google.youtube('v3')
  // Create an authentication client
  const auth = new google.auth.OAuth2(
    client.clientId,
    client.clientSecret,
    client.redirectUri,
  )
  auth.setCredentials(client.credentials)
  return new Promise((resolve, reject) => {
    youtube.search.list(
      {
        auth: auth,
        part: 'snippet',
        type: 'channel',
        q: text,
      },
      function (err, response) {
        if (err) {
          console.error('에러났어: ' + err)
          reject(err)
        } else {
          let searchResults = response.data.items

          if (searchResults.length === 0) {
            resolve([])
          } else {
            const promises = searchResults.map((searchResult) => {
              return new Promise((resolve, reject) => {
                youtube.channels.list(
                  {
                    auth: auth,
                    part: 'statistics',
                    id: searchResult.id.channelId,
                  },
                  function (err, response) {
                    if (err) {
                      console.error('구독자수 불러오기 실패')
                      reject(err)
                    } else {
                      let channel = response.data.items[0]

                      let subscriberCount = channel.statistics.subscriberCount

                      resolve({
                        searchResult: searchResult,
                        subscriberCount: subscriberCount,
                      })
                    }
                  },
                )
              })
            })

            // Wait for all promises to resolve
            Promise.all(promises)
              .then((finalResults) => {
                resolve(finalResults)
              })
              .catch((error) => {
                console.error('에러났어: ' + error)
                reject(error)
              })
          }
        }
      },
    )
  })
}

```

결과
![image](https://github.com/robinyoon-dev/typescript-project/assets/107087958/a266112d-17f2-4398-ba59-84f1495888d2)
