### ISSUE TITLE
첫 화면, 검색 화면 UI 뼈대 구현 & 작동 가능하게 만들기

### ISSUE THREAD

**Issue by robinyoon-dev** [robinyoon-dev/typescript-project#19]
# Description
첫 화면과 검색 화면 UI 뼈대 구현하자. 
그리고 작동 가능하게 만들기

# Todo
- [x]  첫 화면 UI 뼈대 구현하기
- [x]  Authentication 이후 oauth2callback 페이지 자동으로 닫히게 만들기.
- [x]  검색 화면 UI 뼈대 구현하기

**Comment by robinyoon-dev** [comment]
# 알게 된 것: res.setHeader
![image](https://github.com/robinyoon-dev/typescript-project/assets/107087958/57c4bd99-5bc5-4bd2-950d-0acec1e86af6)
