### ISSUE TITLE
시청자 분석 페이지에 데이터 불러오기

### ISSUE THREAD

**Issue by robinyoon-dev** [robinyoon-dev/typescript-project#20]
# Description
서치 후 카드 클릭 시 해당 채널의 시청자 분석 페이지로 이동.
시청자 분석 페이지에 데이터 불러오기.

# Todo
- [x]  시청자 분석 페이지에 채널 정보 불러오기
- [ ]  시청자 분석 페이지에 시청자 정보 불러오기
- [x]  페이지 상단에 채널 정보 보여주기
- [ ]  페이지 하단에 시청자 정보 보여주기

# ETC 
Youtube Reporting API 사용법 관련 사이트
- https://www.any-api.com/googleapis_com/youtubereporting/docs/API_Description
- https://developers.google.com/youtube/reporting/v1/reference/rest?hl=ko
- 채널 보고서: https://developers.google.com/youtube/reporting/v1/reports/channel_reports?hl=ko

**Reporting API가 아닌, Analytics API 사용**
이유: Reporting API는 리포트 데이터를 받으려면 며칠이란 시간이 소요된다.
그러므로 바로 데이터를 받을 수 있는 Analytics API 사용.

참고 사이트: 
- https://www.any-api.com/googleapis_com/youtubeAnalytics/docs/API_Description
- https://brunch.co.kr/@joypinkgom/121
- https://developers.google.com/youtube/analytics/data_model?hl=ko

**Comment by robinyoon-dev** [comment]
# 채널 정보
```javascript
    youtube.channels.list(
      {
        auth: auth,
        part: 'snippet, brandingSettings, contentDetails, statistics, topicDetails',
        id: channelId,
      },
//...
```


참고: https://developers.google.com/youtube/v3/docs/channels/list?hl=ko

```
{
  kind: 'youtube#channel',
  etag: 'dIFkUMqlmWfeLEaLPoKjPPnZ9sY',
  id: 'UC9gxOp_-R78phMHmv2bW_sg',
  snippet: {
    title: '원지의하루',
    description: '여행자 원지의 하루(살이)\n' +
      '한 곳에 머물며 살아가듯 여행하는 것을 좋아합니다\n' +     
      '\n' +
      '🪵🍛 ☕️ 🛌💛\n' +
      ' • Email  :  wonjileelife@gmail.com\n' +
      ' • Instagram  :  https://www.instagram.com/im1g/\n' +     
      ' • Book(저서)  : http://bit.ly/323YAbO\n' +
      ' • 톱밥꼰주(부채널) : https://bit.ly/3zvfsg5\n',
    customUrl: '@im1g',
    publishedAt: '2012-12-11T04:37:55Z',
    thumbnails: { default: [Object], medium: [Object], high: [Object] },
    defaultLanguage: 'ko',
    localized: {
      title: '원지의하루',
      description: '여행자 원지의 하루(살이)\n' +
        '한 곳에 머물며 살아가듯 여행하는 것을 좋아합니다\n' +   
        '\n' +
        '🪵🍛 ☕️ 🛌💛\n' +
        ' • Email  :  wonjileelife@gmail.com\n' +
        ' • Instagram  :  https://www.instagram.com/im1g/\n' +   
        ' • Book(저서)  : http://bit.ly/323YAbO\n' +
        ' • 톱밥꼰주(부채널) : https://bit.ly/3zvfsg5\n'
    },
    country: 'KR'
  },
  contentDetails: {
    relatedPlaylists: { likes: '', uploads: 'UU9gxOp_-R78phMHmv2bW_sg' }
  },
  statistics: {
    viewCount: '136826030',
    subscriberCount: '754000',
    hiddenSubscriberCount: false,
    videoCount: '349'
  },
  topicDetails: {
    topicIds: [ '/m/019_rr', '/g/120yrv6h' ],
    topicCategories: [
      'https://en.wikipedia.org/wiki/Lifestyle_(sociology)',     
      'https://en.wikipedia.org/wiki/Tourism'
    ]
  },
  brandingSettings: {
    channel: {
      title: '원지의하루',
      description: '여행자 원지의 하루(살이)\n' +
        '한 곳에 머물며 살아가듯 여행하는 것을 좋아합니다\n' +   
        '\n' +
        '🪵🍛 ☕️ 🛌💛\n' +
        ' • Email  :  wonjileelife@gmail.com\n' +
        ' • Instagram  :  https://www.instagram.com/im1g/\n' +   
        ' • Book(저서)  : http://bit.ly/323YAbO\n' +
        ' • 톱밥꼰주(부채널) : https://bit.ly/3zvfsg5\n',        
      keywords: '여행유튜버 세계여행 일상브이로그 여행브이로그', 
      defaultLanguage: 'ko',
      country: 'KR'
    },
    image: {
      bannerExternalUrl: 'https://yt3.googleusercontent.com/cVq6k2I77AkvZlkBxDOGa2WEBFh7xQE_5Qx0V6yyQLuSOPg_KQww-PxW6x0_6GYFF2hKV0mu'
    }
  }
```

**Comment by robinyoon-dev** [comment]
# 채널 정보 UI 참고 및 필요한 정보
![image](https://github.com/robinyoon-dev/typescript-project/assets/107087958/5a81ae46-8186-4a25-934e-2ce6acb85a65)

- 배너 이미지: `brandingSettings.image.bannerExternalUrl`


- 프로필 사진: `snippet.thumbnails.default` (썸네일이 프로필사진이려나...?)
```
thumbnails: { default: [Object], medium: [Object], high: [Object] },
```

- 타이틀: `snippet.title`
- description: `snippet.description`
- 카테고리: `topicDetails.topicIds`, `topicDetails.topicCategories`
```
  topicDetails: {
    topicIds: [ '/m/019_rr', '/g/120yrv6h' ],
    topicCategories: [
      'https://en.wikipedia.org/wiki/Lifestyle_(sociology)',     
      'https://en.wikipedia.org/wiki/Tourism'
    ]
  },
```
- SNS 등: 모르겠다.

**Comment by robinyoon-dev** [comment]
https://github.com/robinyoon-dev/typescript-project/issues/22#issue-1751636282

카테고리 추출할 방법은 따로 이슈로 빼놓았다.

**Comment by robinyoon-dev** [comment]
# 리포트 정보 불러오는 중 현재 상황
 
## 다음 에러 발생
```
TypeError: googleapis__WEBPACK_IMPORTED_MODULE_0__.google.youtubeReporting is not a function
```

## 현재 코드

report.js
```
import { google } from 'googleapis'

export default async function handler(req, res) {
  if (req.method === 'POST') {
    const data = req.body
    const { storedAuthData} = data

    try {
      const infoResult = await runSample(storedAuthData)

      res.status(200).json({ infoResult })
    } catch (error) {
      console.error('에러났어: ' + error)
      res.status(500).json({ error: 'Internal server error' })
    }
  }
}

async function runSample(client) {
  const youtubeReporting = google.youtubeReporting('v1')

  const auth = new google.auth.OAuth2(
    client.clientId,
    client.clientSecret,
    client.redirectUri,
  )
  auth.setCredentials(client.credentials)

  //데이터 보고서 생성 요청
  const reportTypeId = 'channel_basic_a2'
  const request = {
    auth: auth,
    requestBody: {
      reportTypeId: reportTypeId,
      name: 'My Report',
      //   startTime: 'START_TIME',
      //   endTime: 'END_TIME',
    },
  }

  return new Promise((resolve, reject) => {
    //jobs.create(): 메서드를 호출하여 채널 또는 콘텐츠 소유자를 위해 생성해야 하는 보고서를 식별합니다. 
    youtubeReporting.jobs.create(request, function (err, response) {
      if (err) {
        console.error('데이터 보고서 생성 실패')
        reject(err)
      } else {
        let channelResults = response.data.items[0]

        resolve({ channelResults })
      }
    })
  })
}

```

**Comment by robinyoon-dev** [comment]
# R을 r로 바꾼 후 그 다음 마주친 에러
```
데이터 보고서 생성 실패
에러났어: Error: Requested entity already exists
```

**Comment by robinyoon-dev** [comment]
# Youtube Analytics API 사용시 다음과 같은 에러 발생.
```
TypeError: googleapis__WEBPACK_IMPORTED_MODULE_0__.google.youtubeanalytics is not a function
```

현재 analytics.js 코드
```javascript
import { google } from 'googleapis'

export default async function handler(req, res) {
  if (req.method === 'POST') {
    const data = req.body
    const { storedAuthData, channelId } = data

    try {
      const infoResult = await runSample(storedAuthData, channelId)

      res.status(200).json({ infoResult })
    } catch (error) {
      console.error('에러났어: ' + error)
      res.status(500).json({ error: 'Internal server error' })
    }
  }
}

async function runSample(client, channelId) {
  const youtubeanalytics = google.youtubeanalytics('v2')

  const auth = new google.auth.OAuth2(
    client.clientId,
    client.clientSecret,
    client.redirectUri,
  )
  auth.setCredentials(client.credentials)

  const request = {
    auth: auth,
    ids: `contentOwner==${channelId}`,
    metrics:
      'views, redViews, estimatedMinutesWatched, estimatedRedMinutesWatched, averageViewDuration, playlistStarts, viewsPerPlaylistStart, averageTimeInPlaylist',
  }

  return new Promise((resolve, reject) => {
    youtubeanalytics.reports.query(request, function (err, response) {
      if (err) {
        console.error('데이터 보고서 생성 실패')
        reject(err)
      } else {
        let analyticsResult = response.data

        resolve({ analyticsResult })
      }
    })
  })
}

```

**Comment by robinyoon-dev** [comment]
# 문제 발생
데이터 보고서 생성 실패
```
데이터 보고서 생성 실패
에러났어: Error: Could not parse content (views, redViews, estimatedMinutesWatched, estimatedRedMinutesWatched, averageViewDuration, playlistStarts, viewsPerPlaylistStart, averageTimeInPlaylist) of field metrics.
```

현재 코드
```javascript
import { google } from 'googleapis'

export default async function handler(req, res) {
  if (req.method === 'POST') {
    const data = req.body
    const { storedAuthData, channelId } = data

    try {
      const infoResult = await runSample(storedAuthData, channelId)

      res.status(200).json({ infoResult })
    } catch (error) {
      console.error('에러났어: ' + error)
      res.status(500).json({ error: 'Internal server error' })
    }
  }
}

async function runSample(client, channelId) {
  const youtubeanalytics = google.youtubeAnalytics('v2')

  const auth = new google.auth.OAuth2(
    client.clientId,
    client.clientSecret,
    client.redirectUri,
  )
  auth.setCredentials(client.credentials)

  const request = {
    auth: auth,
    ids: `contentOwner==${channelId}`,
    metrics:
      'views, redViews, estimatedMinutesWatched, estimatedRedMinutesWatched, averageViewDuration, playlistStarts, viewsPerPlaylistStart, averageTimeInPlaylist',
    //YYYY-MM-DD 형식
    startDate: '2023-06-13', 
    endDate: '2023-06-01',
  }

  return new Promise((resolve, reject) => {
    youtubeanalytics.reports.query(request, function (err, response) {
      if (err) {
        console.error('데이터 보고서 생성 실패')
        reject(err)
      } else {
        let analyticsResult = response.data

        resolve({ analyticsResult })
      }
    })
  })
}

```

**Comment by robinyoon-dev** [comment]
# User activity by subscribed status
https://developers.google.com/youtube/analytics/content_owner_reports#user-activity-by-subscribed-status

**Comment by robinyoon-dev** [comment]
# ids: `channel==${channelId}`
https://developers.google.com/youtube/analytics/channel_reports

**Comment by robinyoon-dev** [comment]
# 해결
  metrics: 'views,likes,dislikes,estimatedRevenue'
metircs에 빈 칸을 제거했더니 되었다.
그런데 또 다른 에러가 나왔는데 바로, 
```
  code: 403,
  errors: [ { message: 'Forbidden', domain: 'global', reason: 'forbidden' } ]
}
에러났어: Error: Forbidden
```

**Comment by robinyoon-dev** [comment]
# 시청자 정보 불러올 방법 없음(Forbidden)
