### ISSUE TITLE
채널 정보 - Description 줄바꿈 처리 구현 및 생략 기능 추가

### ISSUE THREAD

**Issue by robinyoon-dev** [robinyoon-dev/typescript-project#24]
# Description
![image](https://github.com/robinyoon-dev/typescript-project/assets/107087958/74585e52-d78b-4223-bf8c-1b0440240ea5)
![image](https://github.com/robinyoon-dev/typescript-project/assets/107087958/ffeeae9d-16cb-46f0-b900-26d763adb585)

# Todo
- [ ]  디폴트: 한 줄로 생략된 상태로 구현.
- [ ]  버튼 클릭 시 Description 전체 보기 구현.
- [ ] Description의 줄바꿈 정보가 적용되도록 구현하기.
